[package]
name = "dissect-gen-classic"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.9.8"
num-bigint = "0.4.2"
num-traits = "0.2.14"
num-integer = "0.1.44"
rand = "0.5.0"
